branch-protection:
  orgs:
    openshift-service-mesh:
      repos:
        istio:
          branches:
            release-1.20:
              protect: true
              required_pull_request_reviews:
                required_approving_review_count: 1
              unmanaged: false
tide:
  queries:
  - author: maistra-bot
    labels:
    - auto-merge
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    repos:
    - openshift-service-mesh/istio
  - labels:
    - okay to merge
    missingLabels:
    - do-not-merge
    - do-not-merge/hold
    - do-not-merge/work-in-progress
    repos:
    - openshift-service-mesh/istio
    reviewApprovedRequired: true
